version: '2'

services:
  fpm:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/var/www/
    restart: always
    environment:
      - VIRTUAL_HOST=redfoxbot.dev
    networks:
      - dev
      - local

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=telegram
      - POSTGRES_USER=root
    networks:
      - local
    volumes:
      - /usr/local/docker/data/redfoxbot/postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    expose:
      - 6379
    volumes:
      - /usr/local/docker/data/redfoxbot/redis:/data
    networks:
      - local
    command: redis-server --appendonly yes

networks:
  local:
    driver: bridge