version: '2'

services:
  fpm:
    build:
      context: .
      dockerfile: Dockerfile.dev
    links:
      - db
      - redis
    depends_on:
      - db
    volumes:
      - ./:/var/www/
    restart: always
    environment:
      - VIRTUAL_HOST=redfoxbot.dev
    networks:
      - dev
      - rfx

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=telegram
      - POSTGRES_USER=root
    networks:
      - rfx
    volumes:
      - /usr/local/docker/data/redfoxbot/postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "63791:6379"
    volumes:
      - /usr/local/docker/data/redfoxbot/redis:/data
    networks:
      - rfx
    command: redis-server --appendonly yes

networks:
  dev:
    external:
      name: dev-services
  rfx:
    driver: bridge