version: '2'

services:
  fpm:
    build:
      context: .
      dockerfile: Dockerfile.dev
    links:
      - db
      - redis
    volumes:
      - ./:/var/www/
    restart: always
    environment:
      - VIRTUAL_HOST=redfoxbot.dev
    extends:
      file: docker-compose.base.yml
      service: fpm
    networks:
      - dev
      - local

  db:
    extends:
      file: docker-compose.base.yml
      service: db

  redis:
    extends:
      file: docker-compose.base.yml
      service: redis

networks:
  local:
    driver: bridge
  dev:
    external:
      name: dev-services