version: '3.2'

services:
  fpm:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/var/www/
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/status"]
      interval: 1m
      timeout: 10s
    environment:
      - VIRTUAL_HOST=redfoxbot.dev
    networks:
      - dev
      - local

  db:
    image: postgres:latest
    ports:
      - 5431:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1m30s
      timeout: 10s
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=telegram
      - POSTGRES_USER=root
    networks:
      - local
    volumes:
      - /usr/local/docker/data/redfoxbot/postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    expose:
      - 6379
    volumes:
      - /usr/local/docker/data/redfoxbot/redis:/data
    networks:
      - local
    command: redis-server --appendonly yes

networks:
  local:
    driver: bridge
  dev:
    external:
      name: dev-services
