version: '2'

services:
  fpm:
    build:
      context: .
      dockerfile: Dockerfile.dev
    links:
      - db
      - redis
    depends_on:
      - db
    volumes:
      - ./:/var/www/
    restart: always

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=telegram
      - POSTGRES_USER=root
    volumes:
      - ./docker/data/postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "63791:6379"
    volumes:
      - ./docker/data/redis:/data
    command: redis-server --appendonly yes

  lb:
    image: dockercloud/haproxy
    ports:
      - 4430:80
      - 8008:80
    links:
      - fpm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
