<?php
/**
 * Created by PhpStorm.
 * User: akeinhell
 * Date: 18.04.16
 * Time: 11:31.
 */

namespace App\Telegram\Commands;

use App\Telegram\AbstractCommand;
use App\Telegram\Bot;
use App\Telegram\Config;

class KeyboardCommand extends AbstractCommand
{
    public static $description = 'Запуск лисы';

    public static $entities = ['/keyboard'];
    protected $active       = true;
    protected $visible      = false;
    protected $patterns     = [
        '\/start(\s|@redfoxbot\s)',
    ];

    public function execute($payload)
    {
        if (Config::getValue($this->chatId, 'project') === 'Encounter') {
            Bot::action()->sendMessage($this->chatId, '---', null, false, null, Bot::getKeyboard());
        }
        if (Config::getValue($this->chatId, 'project') === 'RedfoxSafari') {
            Bot::action()->sendMessage($this->chatId, '---', null, false, null, Bot::getSafariKeyboard());
        }
    }

    protected function prepare()
    {
        //   parent::prepare(); // TODO: Change the autogenerated stub
    }
}
